// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for android - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBriEwNduY9QPKHmsDxI8tBWGEaY5YPM84',
    appId: '1:409691063278:web:648a13a7f788cf487884ff',
    messagingSenderId: '409691063278',
    projectId: 'flash-chat-bd7e8',
    authDomain: 'flash-chat-bd7e8.firebaseapp.com',
    storageBucket: 'flash-chat-bd7e8.appspot.com',
    measurementId: 'G-B739GN1N6S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWAn8dYKy6A0gjx9bMrcdApPjXt93j1T4',
    appId: '1:409691063278:ios:8074a3e4e742d1c87884ff',
    messagingSenderId: '409691063278',
    projectId: 'flash-chat-bd7e8',
    storageBucket: 'flash-chat-bd7e8.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWAn8dYKy6A0gjx9bMrcdApPjXt93j1T4',
    appId: '1:409691063278:ios:8074a3e4e742d1c87884ff',
    messagingSenderId: '409691063278',
    projectId: 'flash-chat-bd7e8',
    storageBucket: 'flash-chat-bd7e8.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBriEwNduY9QPKHmsDxI8tBWGEaY5YPM84',
    appId: '1:409691063278:web:50dacd2f9ed7b0ff7884ff',
    messagingSenderId: '409691063278',
    projectId: 'flash-chat-bd7e8',
    authDomain: 'flash-chat-bd7e8.firebaseapp.com',
    storageBucket: 'flash-chat-bd7e8.appspot.com',
    measurementId: 'G-M8KYFHE4JV',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBriEwNduY9QPKHmsDxI8tBWGEaY5YPM84',
    appId: '1:409691063278:web:50dacd2f9ed7b0ff7884ff',
    messagingSenderId: '409691063278',
    projectId: 'flash-chat-bd7e8',
    // authDomain: 'flash-chat-bd7e8.firebaseapp.com',
    // storageBucket: 'flash-chat-bd7e8.appspot.com',
    // measurementId: 'G-M8KYFHE4JV',
  );
}
